### ISSUE TITLE
XSS vulnerability in team name

### ISSUE THREAD

**Issue by rkkautsar** [farisv/CTFd-Private-Registration#2]
Team name containing html tags displayed as is after imported from csv

**Comment by farisv** [comment]
Only admin can upload CSV (with CSRF protection) so if admin cause XSS through this feature, it's similar with admin cause XSS through `admin/pages?mode=create`.

But, now I'm thinking someone may trick admin to upload malicious CSV so I think this should be fixed. Thank you for report!

**Comment by farisv** [comment]
I just realized, any script tag in team name will not processed by browser because it's appended in the middle. Some HTML tags like `<b>` or `<table>` will be processed though, so it will affect the display. Do you want to create PR for this?
